name: Unit Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:

env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}


jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - name: Install
        run: |
          sudo apt-get install -y libcurl4-openssl-dev
          sudo apt-get install -y libmagick++-dev
          Rscript -e 'install.packages("remotes")'
          Rscript -e 'remotes::install_github("rstudio/renv")'
          Rscript -e "renv::install()"

      - name: Test
        run: Rscript -e "devtools::test()"

      - name: coverage
        run: Rscript -e "library(covr); codecov()"
